I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script call
    call reincarnation(twitch)
  File "game/reincarnation.rpy", line 10, in script
    thresh.C 'where is he?'
Exception: Sayer 'thresh.C' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script call
    call reincarnation(twitch)
  File "game/reincarnation.rpy", line 10, in script
    thresh.C 'where is he?'
  File "/home/mary/arch/projects/renpy-8.2.3-sdk/renpy/ast.py", line 2560, in execute
    Say.execute(self)
  File "/home/mary/arch/projects/renpy-8.2.3-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/home/mary/arch/projects/renpy-8.2.3-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'thresh.C' is not defined.

Linux-6.9.5-arch1-1-x86_64-with-glibc2.39 x86_64
Ren'Py 8.2.3.24061702
The time I got reincarnated as a spaceglider 1.0
Tue Jun 25 14:28:30 2024
